name: AIMCME
main: com.mcmiddleearth.ai.mcme.AIMCME
version: ${project.version}
website: ${project.url}
authors: [DonoA]
description: npc conversations.
author: DonoA
commands:
  say:
    usage: /say <words>